# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmd < Formula
  desc "Database migration using REL"
  homepage "https://go-rel.github.io/"
  version "0.40.0"
  license "MIT"

  depends_on "golang" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-rel/cmd/releases/download/v0.40.0/cmd_0.40.0_Darwin_x86_64.tar.gz"
      sha256 "b8ef4664224d3381849cb0e3e7522c8a90ba37510d3c462907fe40bd7876d600"

      def install
        bin.install "cmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-rel/cmd/releases/download/v0.40.0/cmd_0.40.0_Darwin_arm64.tar.gz"
      sha256 "5cbbb4d67cb888b0129a2b58a0dd3e9e118a982cf09a098f86624e887bd519ba"

      def install
        bin.install "cmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-rel/cmd/releases/download/v0.40.0/cmd_0.40.0_Linux_arm64.tar.gz"
      sha256 "606bd34a3a6dfc75b5ab5b58b28a6fb0128ee50c5a8121eb2d7b58ec67c4983c"

      def install
        bin.install "cmd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-rel/cmd/releases/download/v0.40.0/cmd_0.40.0_Linux_armv6.tar.gz"
      sha256 "2a33d7459e4f02566b2a15297c12ce28088b98c88d664425ff62afc28b43ec03"

      def install
        bin.install "cmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-rel/cmd/releases/download/v0.40.0/cmd_0.40.0_Linux_x86_64.tar.gz"
      sha256 "864142b6a821aec39b31052ee6989e0d31c1d1c80edfd2a5f4583d1b9e07b2a2"

      def install
        bin.install "cmd"
      end
    end
  end
end
