# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rel < Formula
  desc "Database migration using REL"
  homepage "https://go-rel.github.io/"
  version "0.33.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-rel/rel/releases/download/v0.33.0/rel_0.33.0_Darwin_arm64.tar.gz"
      sha256 "6e14f914430a632fd3f3922ed5d18c6a5d0610e924ba691b151841acde15fb2d"

      def install
        bin.install "rel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-rel/rel/releases/download/v0.33.0/rel_0.33.0_Darwin_x86_64.tar.gz"
      sha256 "945a80313147e51cf8288d47a6f30213eb9244fd3abcfeceb207bed9f467eaad"

      def install
        bin.install "rel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-rel/rel/releases/download/v0.33.0/rel_0.33.0_Linux_armv6.tar.gz"
      sha256 "4cd1fd320e87c310d53ee9a47cebb8573df53fdeb7b7f2bee962a8b09af7f0b8"

      def install
        bin.install "rel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-rel/rel/releases/download/v0.33.0/rel_0.33.0_Linux_arm64.tar.gz"
      sha256 "8b2239e5da69ebd75c93ad75ae7c5f89c2ec887f3f808b30215c7febbffa970a"

      def install
        bin.install "rel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-rel/rel/releases/download/v0.33.0/rel_0.33.0_Linux_x86_64.tar.gz"
      sha256 "afea9aef1df44fd852a02f2537d0cf962df30733c8281188c68c3792536bec7a"

      def install
        bin.install "rel"
      end
    end
  end

  depends_on "golang" => :optional
end
